sudo: required

language: node_js

node_js:
  - "9"

services:
  - docker

install:
  - sudo apt-get install openjdk-8-jdk -y
  - sudo apt-get install maven -y 
  - npm install

script:
  - gulp
  - mvn clean assembly:assembly -DdescriptorId=jar-with-dependencies
  - mv target/pdfutils-*-jar-with-dependencies.jar dist/pdfutils.jar
  - docker build -t qinling/md2pdf:latest .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push qinling/md2pdf:latest
  - docker logout
