sudo: required

language: node_js

node_js:
  - "9"

services:
  - docker

install:
  - sudo apt-get install openjdk-8-jdk -y
  - sudo apt-get install maven -y 
  - npm install

script:
  - ./build.sh
  - docker build -t qinling/md2pdf:latest .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push qinling/md2pdf:latest
  - docker logout
